@baseUrl = http://localhost:3000
@email = user@example.com
@password = password

### Authentication sign in

# @name signIn
POST {{baseUrl}}/authentication/sign-in HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Authentication sign up

# @name signUp
POST {{baseUrl}}/authentication/sign-up HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "name": "User",
  "password": "{{password}}",
  "passwordConfirm": "{{password}}",
  "phone": "67991768018"
}
