@baseUrl = http://localhost:3000


###

# @import ./authentication.http
 

### Create a client

# @forceRef signIn
POST {{baseUrl}}/clients HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Client Name",
  "phone": "67991768018"
}

### Update a client

# @forceRef signIn
PATCH {{baseUrl}}/clients/b8604331-8e0f-47ca-84f6-2d1e554ea2a1 HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Client Name",
  "phone": "67991768014"
}

### Get a client

# @forceRef signIn
GET {{baseUrl}}/clients/b8604331-8e0f-47ca-84f6-2d1e554ea2a1 HTTP/1.1
Authorization: Bearer {{accessToken}}

### Get all clients

# @forceRef signIn
GET {{baseUrl}}/clients HTTP/1.1
Authorization: Bearer {{accessToken}}
