@baseUrl = http://localhost:3000
@email = user@example.com
@password = password

@accessToken = {{signIn.response.body.data.access_token}}

@procedureId = ec7d4d56-0658-41d5-b8c0-71d6b7401f06

@clientId = 8aae51df-a9e1-4a15-88cd-083653afb4f1

@procedureId = 8aae51df-a9e1-4a15-88cd-083653afb4f1

### Authentication sign in

# @name signIn
POST {{baseUrl}}/authentication/sign-in HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Create a procedure

POST {{baseUrl}}/procedures HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Procedure Name",
  "price": 1000,
  "returnDays": 15,
  "durationMinutes": 160
}

### Update a procedure

PATCH {{baseUrl}}/procedures/{{procedureId}} HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "clientId": "{{clientId}}",
  "procedureId": "{{procedureId}}",
  "startTime": "19:11",
  "endTime": "21:10"
}

### Get a procedure

GET {{baseUrl}}/procedures/{{procedureId}} HTTP/1.1
Authorization: Bearer {{accessToken}}

### Get all procedures

GET {{baseUrl}}/procedures HTTP/1.1
Authorization: Bearer {{accessToken}}

### Delete a procedure
DELETE {{baseUrl}}/procedures/{{procedureId}} HTTP/1.1
Authorization: Bearer {{accessToken}}