@baseUrl = http://localhost:3000
@email = user@example.com
@password = password

@accessToken = {{signIn.response.body.data.access_token}}

@scheduleTemplateId = ec7d4d56-0658-41d5-b8c0-71d6b7401f06

### Authentication sign in

# @name signIn
POST {{baseUrl}}/authentication/sign-in HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Create a schedule-template

POST {{baseUrl}}/schedule-templates HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "dayOfWeek": "monday",
  "startTime": "19:11",
  "endTime": "20:12"
}

### Update a schedule-template

PATCH {{baseUrl}}/schedule-templates/{{scheduleTemplateId}} HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "dayOfWeek": "monday",
  "endTime": "21:10"
}

### Get a schedule-template

GET {{baseUrl}}/schedule-templates/{{scheduleTemplateId}} HTTP/1.1
Authorization: Bearer {{accessToken}}

### Get all schedule-templates

GET {{baseUrl}}/schedule-templates HTTP/1.1
Authorization: Bearer {{accessToken}}

### Delete a schedule-template
DELETE {{baseUrl}}/schedule-templates/{{scheduleTemplateId}} HTTP/1.1
Authorization: Bearer {{accessToken}}